version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=timetracker
      - DB_USER=postgres
      - DB_PASSWORD=Shorlotik003
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shorlotik003
    ports:
      - "5432:5432"
