version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shorlotik003
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
