version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shorlotik003
    ports:
      - "5432:5432"
    networks:
      - backend
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timetracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Shorlotik003
    networks:
      - backend

networks:
  backend:
    driver: bridge
